name: Push to GitHub Pages
on:
  push:
    branches:
      - feature/hugo

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          HUGO_VERSION: 0.57.2
          TARGET_REPO: goodhamgupta/goodhamgupta.github.io
          TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          CNAME: goodhamgupta.github.io
